/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

//import java.util.ArrayList;
//import java.util.List;

public class Player {
  public static void DrowDeck(String[] args) {
    // semonster2 monster = new semonster2(1, 2);
    // List<String> monsters=new ArrayList<String>();
    // String ArrayList[] = { monster.summonMonster(1) }; // 松尾タイピスト終了地点
  }
}
